// Add a new game by adding one entry to this array — the dashboard builds itself from it.
// preview: "bird" and "wordle" have built-in live-preview animations (see script.js).
// Leave preview out (or use an unrecognized value) to fall back to a plain icon card.
const GAMES = [
  {
    title: "Pretty Bird",
    tagline: "Tap, flap, don't crash",
    description: "A flappy little bird dodges cats and pipes in a cozy pastel sky. Simple to learn, hard to put down.",
    path: "games/pretty-bird/index.html",
    icon: "games/pretty-bird/images/bird1up.png",
    accent: "#2fb6c9",
    preview: "bird",
    previewAssets: {
      up: "games/pretty-bird/images/bird1up.png",
      down: "games/pretty-bird/images/bird1down.png",
      cats: [
        "games/pretty-bird/images/cat1.png",
        "games/pretty-bird/images/cat2.png",
        "games/pretty-bird/images/cat3.png",
        "games/pretty-bird/images/cat4.png",
      ],
    },
  },
  {
    title: "Wordle",
    tagline: "Guess the word, one bloom at a time",
    description: "The classic 5-letter word guessing game with a pink twist — hints, definitions, and a daily challenge.",
    path: "games/wordle-land/index.html",
    icon: "games/wordle-land/favicon-192.png",
    accent: "#ec4899",
    preview: "wordle",
    previewWord: "PINKY",
  },
  {
    title: "Tango",
    tagline: "Balance the grid, hearts and stars",
    description: "Fill the grid with hearts and stars so no three match in a row and every line stays balanced.",
    path: "games/tango/index.html",
    icon: "games/tango/favicon.svg",
    accent: "#8a5fe0",
    preview: "tango",
  },
  {
    title: "Queens",
    tagline: "One crown per color, none too close",
    description: "Place a crown in every row, column, and color region — no two crowns may ever touch.",
    path: "games/queens/index.html",
    icon: "games/queens/favicon.svg",
    accent: "#d6336c",
    preview: "queens",
  },
  {
    title: "Minesweeper",
    tagline: "Tiptoe around the kittens",
    description: "The classic tile-clearing puzzle, reskinned with paw prints and a soft pastel palette.",
    path: "games/minesweeper/index.html",
    icon: "games/minesweeper/favicon.svg",
    accent: "#f2994a",
    preview: "minesweeper",
  },
  {
    title: "Block Blast",
    tagline: "Fill lines, chase your best score",
    description: "Drag colorful blocks onto an 8×8 grid and clear full rows and columns before it fills up. Simple to start, addictive to master.",
    path: "games/block-blast/index.html",
    icon: "games/block-blast/favicon.svg",
    accent: "#3a86ff",
    preview: "blockblast",
  },
];
